# Generated by Django 3.0.3 on 2020-06-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_to_publish']},
        ),
    ]
