# Generated by Django 3.0.3 on 2020-02-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Loading..', 'Loading..'), ('Drafted', 'Drafted'), ('Published', 'Published')], default='Loadind..', help_text='The state of this post. Published or Drafted', max_length=50, verbose_name='Status'),
        ),
    ]
