# Generated by Django 3.0.3 on 2020-02-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Extra Phone number'),
        ),
    ]
